### ISSUE TITLE
New version doesnt work any more

### ISSUE THREAD

**Issue by chriswattz** [disenone/UE.AIChatPlus.Public#1]
![Screenshot 2024-11-27 123607](https://github.com/user-attachments/assets/3f2333c8-27e1-45f0-9041-a71b7978a7ca)

I bought this plugin yestureday and setted a small scene up and it worked. Today i updated and the scene does not work any more in unreal 5.3. I tried an unreal 5.4 new scene and also the same error : Error:
Message[FAIChatPlusCllama_Manager is Invalid.]   (I gave 4 Stars as a rating for this plugin yestureday)

**Comment by disenone** [comment]
Sorry for the error. I will check this out ASAP

**Comment by disenone** [comment]
@chriswattz 
hi, I have sumitted a new version to fix the error. 
You will see it after Fab have reviewed it, which means 1-2 days usually.
